# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Something Witty
tagline:          My Code Blog
url:              http://jackmc.github.io
paginate:         5
baseurl:          /
author:
  name:           Jack McCracken
  url:            http://twitter.com/koalamedian
  email:          jackamc19@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
